Make `IsUserAccountVariables` cloneable (#1705)
# Summary

This PR makes adds `Clone` derive for `IsUserAccountVariables`.
`IsUserAccountVariables` must implement `Clone` in order to be able to
be used in the upcoming version of `fuels-accounts` where the `query`
function requires `Vars` generic parameter to be `Clone`able.

```
error[E0277]: the trait bound `IsUserAccountVariables: Clone` is not satisfied
   --> /.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/fuels-accounts-0.76.0/src/provider/retryable_client.rs:391:24
    |
391 |         let response = self.client.query(query).await?;
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Clone` is not implemented for `IsUserAccountVariables`
    |
note: required by a bound in `FuelClient::query`
   --> /.cargo/git/checkouts/fuel-core-f7771bf68a43277a/cc74bdc/crates/client/src/client.rs:540:34
    |
535 |     pub async fn query<ResponseData, Vars>(
    |                  ----- required by a bound in this associated function
...
540 |         Vars: serde::Serialize + Clone + QueryVariables + Send + 'static,
    |                                  ^^^^^ required by this bound in `FuelClient::query`
help: consider annotating `IsUserAccountVariables` with `#[derive(Clone)]`
    |
411 +     #[derive(Clone)]
412 |     pub struct IsUserAccountVariables {
```

# Checklist

- [x] All **changes** are **covered** by **tests** (or not applicable)
- [x] All **changes** are **documented** (or not applicable)
- [x] I **reviewed** the **entire PR** myself (preferably, on GH UI)
- [x] I **described** all **Breaking Changes** (or there's none)